config/routes.rb
Rails.application.routes.draw do
  resources :posts do
    resources :comments
  end
  devise_for :users
  resources :users
  resources :friend_requests
  resources :friendships, only: [:create, :destroy]
  resources :comments
  
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  root to: "posts#index"
end

app/models/comment.rb
class Comment < ApplicationRecord

  belongs_to :user
  belongs_to :commentable, polymorphic: true
  
end

app/controllers/comments_controller.rb
class CommentsController < ApplicationController
  before_action :authenticate_user!
  
  def new
    @post = Post.find(params[:post_id])
  end

  def create
    @comment = current_user.comments.build(comment_params)
    flash.alert = "Error: #{@comment.errors.full_messages.join}" unless @comment.save
    redirect_to post_path(@comment.commentable_id)
  end

  def destroy
    comment = Comment.find(params[:id])
    comment.destroy
    redirect_to root_path
  end
  
  private
  
  def comment_params
    params.require(:comment).permit(:body, :commentable_id, :commentable_type)
  end
end

app/views/comments/_comment.html.erb
<% post.comments.each do |comment| %>
    <div class="card bg-light" style="margin-bottom:10px;">
      <div class="card-body" style="padding:8px">
        <strong><%= link_to (User.find(comment.user_id).first_name + " " + User.find(comment.user_id).last_name), user_path(comment.user_id) %></strong>
        <%= comment.body %>
        <br>
        <small class="text-muted"><%= comment.created_at.in_time_zone("America/New_York").strftime("%B %d, %Y at %l:%M %P") %></small>
        <% if comment.user.id == current_user.id %>
      <div class="d-inline-block float-right"data-controller="posts">  
        <%= button_to comment, method: :delete, class: "btn btn-danger btn-sm", data: { action: "click->posts#delete" } do %>
          <div><span><svg xmlns="http://www.w3.org/2000/svg" width="16" height="16" fill="currentColor" class="bi bi-trash3-fill" viewBox="0 0 16 16">
  <path d="M11 1.5v1h3.5a.5.5 0 0 1 0 1h-.538l-.853 10.66A2 2 0 0 1 11.115 16h-6.23a2 2 0 0 1-1.994-1.84L2.038 3.5H1.5a.5.5 0 0 1 0-1H5v-1A1.5 1.5 0 0 1 6.5 0h3A1.5 1.5 0 0 1 11 1.5Zm-5 0v1h4v-1a.5.5 0 0 0-.5-.5h-3a.5.5 0 0 0-.5.5ZM4.5 5.029l.5 8.5a.5.5 0 1 0 .998-.06l-.5-8.5a.5.5 0 1 0-.998.06Zm6.53-.528a.5.5 0 0 0-.528.47l-.5 8.5a.5.5 0 0 0 .998.058l.5-8.5a.5.5 0 0 0-.47-.528ZM8 4.5a.5.5 0 0 0-.5.5v8.5a.5.5 0 0 0 1 0V5a.5.5 0 0 0-.5-.5Z"/>
</svg></span></div>
        <% end %>
      </div>  
    <% end %>
      </div>  
    </div>
<% end %>

app/views/comments/_form.html.erb
<%= form_with(model: comment, url: comments_path) do |form| %>
  <%= form.hidden_field :commentable_id, value: comment.commentable_id %>
  <%= form.hidden_field :commentable_type, value: comment.commentable_type %>

  <div class="form-group">
    <%= %>
    <%= form.text_area :body, autofocus: true, placeholder: "Write a comment...", class: "form-control" %>
  </div>
  <div>
    <%= form.submit "Submit comment", class: "btn btn-primary" %>
    
  </div>
<% end %>