config/routes.rb
Rails.application.routes.draw do
  resources :posts do
    resources :comments
  end
  devise_for :users
  resources :users
  resources :friend_requests
  resources :friendships, only: [:create, :destroy]
  resources :comments
  
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  root to: "posts#index"
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

  has_many :posts,
           dependent: :destroy

  has_many :friend_requests,
           foreign_key: :requester_id,
           dependent: :destroy

  has_many :requested_friends,
           through: :friend_requests,
           source: :recipient

  has_many :friend_invitations,
           foreign_key: :recipient_id,
           class_name: :FriendRequest,
           dependent: :destroy

  has_many :requesting_friends,
           through: :friend_invitations,
           source: :requester

  has_many :friendships,
           ->(user) { unscope(:where).where('friend_a_id = ? OR friend_b_id = ?', user.id, user.id) },
          dependent: :destroy

  has_many :comments,
           dependent: :destroy


  def friends(id)
    list_a = Friendship.where(friend_a_id: id)
    list_b = Friendship.where(friend_b_id: id)
    list_a + list_b
  end

  def friend?(user_id, current_user_id)
    list_a = Friendship.where(friend_a_id: user_id, friend_b_id: current_user_id)
    list_b = Friendship.where(friend_b_id: user_id, friend_a_id: current_user_id)
    list_a[0].nil? == false || list_b[0].nil? == false
  end

  def friend_already_requested?(user_id, current_user_id)
    list = []
    User.find(current_user_id).friend_requests.each do |request|
      if user_id == request.recipient_id 
        list << request.recipient_id
      end
    end
    list[0].nil? == false
  end

  def friend_already_invited?(user_id, current_user_id)
    list = []
    User.find(current_user_id).friend_invitations.each do |request|
      if user_id == request.requester_id 
        list << request.requester_id
      end
    end
    list[0].nil? == false
  end

end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :set_user, only: %i[ show edit update destroy ]
  before_action :authenticate_user!

  def index
    @users = User.all
  end

  def create
  end

  def show
    @friend_request 
  end

  def update
    respond_to do |format|
      if @user.update(user_params)
        format.html { redirect_to user_url(@user), notice: "Profile was successfully updated." }
        format.json { render :show, status: :ok, location: @user }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @user.errors, status: :unprocessable_entity }
      end
    end
  end

  def destroy
    if Friendship.find_by(friend_b_id: current_user.id, friend_a_id: @user.id).nil?
      @friendship = Friendship.destroy_by(friend_a_id: current_user.id, friend_b_id: @user.id)
      respond_to do |format|
        
          format.html { redirect_to user_url(@user), notice: "Unfriend successful." }
          format.json { render :show, status: :ok, location: @user }
      end
    elsif Friendship.find_by(friend_a_id: current_user.id, friend_b_id: @user.id).nil?
      @friendship = Friendship.destroy_by(friend_b_id: current_user.id, friend_a_id: @user.id)
      respond_to do |format|
        
          format.html { redirect_to user_url(@user), notice: "Unfriend successful." }
          format.json { render :show, status: :ok, location: @user }
      end
    end
  end

  private

  def set_user
    @user = User.find(params[:id])
  end

  def user_params
    params.require(:user).permit(:first_name, :last_name, :email, :description, :location, :origin, :occupation, :education, :birthday, :description)
  end
end

app/views/users/_about.html.erb
<div class="card">
  <div class="card-body">
      <% if user.description.nil? && current_user == user || user.description == "" && current_user == user %>
        <%= form_with(model: user) do |form| %>
          <div class="form-group">
            <%= form.text_area :description,
                                autocomplete: :off,
                                placeholder: "Describe who you are",
                                class:'form-control' %>
          </div>
          <div class="actions mb-3">
            <%= form.submit "Save", class:'btn btn-primary btn-sm' %>
          </div>
        <% end %>
      <% elsif current_user == user %>
        <p><%= user.description %></p>
        <%= form_with(model: user) do |form| %>
          <div class="form-group">
            <%= form.hidden_field :description, value: "" %>
          </div>
          <div class="actions mb-3">
            <%= form.submit "Clear description", class:'btn btn-outline-primary btn-sm' %>
          </div>
        <% end %>
      <% else %>  
        <% unless user.description == "" || user.description== nil %>
          <p><%= user.description %></p>
        <% end %>
      <% end %>
    <% unless user.location == "" || user.location == nil %>
      <p>Lives in <strong><%= user.location %></strong></p>
    <% end %>
    <% unless user.origin == "" || user.origin == nil %>
      <p>From <strong><%= @user.origin %></strong></p>
    <% end %>
    <% unless user.occupation == "" || user.occupation == nil %>
      <p>Works at <strong><%= user.occupation %></strong></p>
    <% end %>
    <% unless user.education == "" || user.education == nil %>
      <p>Studied at <strong><%= user.education %></strong></p>
    <% end %>
    <% unless user.birthday == "" || user.birthday == nil %>
      <p>Birthday - <strong><%= user.birthday.strftime("%B %d, %Y") %></strong></p>
    <% end %>
    
  </div>
</div>

app/views/users/_all_users.html.erb
<% users.each do |user| %> 
    <% unless user.id == current_user.id || 
    current_user.friend_invitations.where(requester_id: user.id)[0].nil? == false ||
    current_user.friend_requests.where(recipient_id: user.id)[0].nil? == false ||
    user.friend?(user.id, current_user.id) %>     
     <div class="card" style="margin: 10px;">
        <div class="card-header">
            <%= link_to (user.first_name + " " + user.last_name), user_path(user.id)%>
            
        </div>
        <div class="card-body">
          <%= button_to friend_requests_path, method: :post, params: { recipient_id: user.id }, class:"btn btn-primary" do %>
            <div><svg xmlns="http://www.w3.org/2000/svg" width="16" height="16" fill="currentColor" class="bi bi-person-plus-fill" viewBox="0 0 16 16">
              <path d="M1 14s-1 0-1-1 1-4 6-4 6 3 6 4-1 1-1 1H1zm5-6a3 3 0 1 0 0-6 3 3 0 0 0 0 6z"/>
              <path fill-rule="evenodd" d="M13.5 5a.5.5 0 0 1 .5.5V7h1.5a.5.5 0 0 1 0 1H14v1.5a.5.5 0 0 1-1 0V8h-1.5a.5.5 0 0 1 0-1H13V5.5a.5.5 0 0 1 .5-.5z"/>
              </svg>
              Send friend request
            </div>
          <% end %>


            
        </div>
    </div>    
       
    <% end %>
<% end %>

app/views/users/_description_form.html.erb
<%= form_with(model: user) do |form| %>
          <% if user.errors.any? %>
            <div style="color: red">
              <h2><%= pluralize(user.errors.count, "error") %> prohibited this friend from being saved:</h2>
        
              <ul>
                <% user.errors.each do |error| %>
                  <li><%= error.full_message %></li>
                <% end %>
              </ul>
            </div>
          <% end %>
          <div class="form-group">
            <%= form.text_area :description,
                                autocomplete: :off,
                                placeholder: "Tell the world about yourself!",
                                class:'form-control' %>
          </div>
          <div class="actions mb-3">
          
            <%= form.submit "Submit", class:'btn btn-primary' %>
          </div>

app/views/users/_form.html.erb
<div class="card shadow-sm mx-auto" style="max-width:600px">
  <h2 class="card-header">Update profile</h2> 
    <div class="card-body"> 
      <%= form_with(model: user) do |form| %>
        <% if user.errors.any? %>
          <div style="color: red">
            <h2><%= pluralize(user.errors.count, "error") %> prohibited this friend from being saved:</h2>
      
            <ul>
              <% user.errors.each do |error| %>
                <li><%= error.full_message %></li>
              <% end %>
            </ul>
          </div>
        <% end %>
        <em><p> All information is optional </p></em>
        <div class="field">
          <%= form.text_field :first_name,  
                              autocomplete: "first_name", 
                              class:'form-control'%>
        </div>
        <br>
        <div class="field">
          
          <%= form.text_field :last_name,  
                              autocomplete: "last_name", 
                              class:'form-control'%>
        </div>
        <br>
        <div class="field">
          <%= form.text_field :location,  
                              autocomplete: "location",
                              placeholder: "Where do you live?", 
                              class:'form-control'%>
        </div>
        <br>
        <div class="field">
          <%= form.text_field :origin,  
                              autocomplete: "origin",
                              placeholder: "Where did you grow up?",
                              class:'form-control' %>
        </div>
        <br>
        <div class="field">
          <%= form.text_field :occupation,  
                              autocomplete: "occupation",
                              placeholder: "Where do you work?",
                              class:'form-control' %>
        </div>
        <br>
        <div class="field">
          <%= form.text_field :education,  
                              autocomplete: "education",
                              placeholder: "Where did you go to school?",
                              class:'form-control' %>
        </div>
        <br>
        <div class="field">
        <%= form.label "Birthday"%>
        <%= form.date_field :birthday,  
                             autocomplete: "birthday",
                             placeholder: "Birthday",
                             class:'form-control' %>
        </div>
        <br>
        <div class="actions">
          <%= form.submit "Update", class:'btn btn-primary'%>
          <% if current_user.posts.empty? %> 
            <%= link_to "Skip for now", root_path, class:'btn btn-secondary'%>
          <% else %>  
            <%= link_to "Back", :back, class:'btn btn-secondary'%>
          <% end %>
        </div>
      <% end %>
    </div>
  </div>
</div>

app/views/users/_friend_requests.html.erb
<% if current_user.friend_invitations[0].nil? %>
    <p>You don't have any pending friend requests right now.</p>
<% else %>    
  <% current_user.friend_invitations.each do |invitation| %>
    <div class="card" style="margin: 10px;">
      <div class="card-header">
        <%= link_to (User.find(invitation.requester_id).first_name + " " + User.find(invitation.requester_id).last_name), user_path(invitation.requester_id) %>
        
      </div>  
      <div class="card-body">
        <%= button_to friendships_path, method: :post, params: { friend_b_id: User.find(invitation.requester_id).id }, class:"btn btn-success" do %>
          <div><svg xmlns="http://www.w3.org/2000/svg" width="16" height="16" fill="currentColor" class="bi bi-person-plus-fill" viewBox="0 0 16 16">
            <path d="M1 14s-1 0-1-1 1-4 6-4 6 3 6 4-1 1-1 1H1zm5-6a3 3 0 1 0 0-6 3 3 0 0 0 0 6z"/>
            <path fill-rule="evenodd" d="M13.5 5a.5.5 0 0 1 .5.5V7h1.5a.5.5 0 0 1 0 1H14v1.5a.5.5 0 0 1-1 0V8h-1.5a.5.5 0 0 1 0-1H13V5.5a.5.5 0 0 1 .5-.5z"/>
            </svg>
            Accept friend request
          </div>
        <% end %>
      </div>
    </div>
    <br>
  <% end %>
<% end %> 

app/views/users/_friends.html.erb
<% user.friends(user.id).each do |friend| %>
  <div class="card" style="margin: 10px;">
    <div class="card-header">
      <% if user.id == friend.friend_a_id %>
        <%= link_to (User.find(friend.friend_b_id).first_name + " " + User.find(friend.friend_b_id).last_name), user_path(friend.friend_b_id)%>
      <% else %>
        <%= link_to (User.find(friend.friend_a_id).first_name + " " + User.find(friend.friend_a_id).last_name), user_path(friend.friend_a_id)%>
      <% end %>
    </div>
    <div class="card-body">
      <% if user.id == friend.friend_a_id %>
        <%= link_to user_path(friend.friend_b_id), class: "btn btn-primary" do %>
          <div><svg xmlns="http://www.w3.org/2000/svg" width="16" height="16" fill="currentColor" class="bi bi-person-square" viewBox="0 0 16 16">
            <path d="M11 6a3 3 0 1 1-6 0 3 3 0 0 1 6 0z"/>
            <path d="M2 0a2 2 0 0 0-2 2v12a2 2 0 0 0 2 2h12a2 2 0 0 0 2-2V2a2 2 0 0 0-2-2H2zm12 1a1 1 0 0 1 1 1v12a1 1 0 0 1-1 1v-1c0-1-1-4-6-4s-6 3-6 4v1a1 1 0 0 1-1-1V2a1 1 0 0 1 1-1h12z"/>
            </svg>
            View profile
          </div>
        <% end %>
        
      <% else %>
      <%= link_to user_path(friend.friend_a_id), class: "btn btn-primary" do %>
        <div><svg xmlns="http://www.w3.org/2000/svg" width="16" height="16" fill="currentColor" class="bi bi-person-square" viewBox="0 0 16 16">
          <path d="M11 6a3 3 0 1 1-6 0 3 3 0 0 1 6 0z"/>
          <path d="M2 0a2 2 0 0 0-2 2v12a2 2 0 0 0 2 2h12a2 2 0 0 0 2-2V2a2 2 0 0 0-2-2H2zm12 1a1 1 0 0 1 1 1v12a1 1 0 0 1-1 1v-1c0-1-1-4-6-4s-6 3-6 4v1a1 1 0 0 1-1-1V2a1 1 0 0 1 1-1h12z"/>
          </svg>
          View profile
        </div>
        <% end %>

      <% end %>
    </div>
  </div>
  
<% end %>

app/views/users/_posts.html.erb
<% user.posts.each do |post| %>
      <%= render post %>
    <% end %>
    <br>
    <%= link_to "Back", :back , class: "btn btn-secondary" %>
    <% if current_user == user %>
      <%= link_to 'Update Account Information', edit_user_registration_path, class: "btn btn-secondary" %>
    <% end %>
    </div>

app/views/users/_sent_requests.html.erb
<% if current_user.friend_requests[0].nil? %>
    <p>All of your friend requests have been accepted!</p>
<% else %> 
  <% current_user.friend_requests.each do |request| %>
    <div class="card" style="margin: 10px;">
      <div class="card-header">
        <%= link_to (User.find(request.recipient_id).first_name + " " + User.find(request.recipient_id).last_name), user_path(request.recipient_id) %>
      </div>
      <div class="card-body">
        <div class="btn btn-secondary" style="pointer-events: none"><svg xmlns="http://www.w3.org/2000/svg" width="16" height="16" fill="currentColor" class="bi bi-person-check-fill" viewBox="0 0 16 16">
          <path fill-rule="evenodd" d="M15.854 5.146a.5.5 0 0 1 0 .708l-3 3a.5.5 0 0 1-.708 0l-1.5-1.5a.5.5 0 0 1 .708-.708L12.5 7.793l2.646-2.647a.5.5 0 0 1 .708 0z"/>
          <path d="M1 14s-1 0-1-1 1-4 6-4 6 3 6 4-1 1-1 1H1zm5-6a3 3 0 1 0 0-6 3 3 0 0 0 0 6z"/>
          </svg>
            Request sent
        </div>
      </div>
    </div>
    
  <% end %>
<% end %>

app/views/users/edit.html.erb
<%= render 'form', user: @user %>

app/views/users/index.html.erb
<div class="card shadow-sm mx-auto" style="max-width:600px">
  <div class="card-body">
    <h2> <%= current_user.first_name%> <%= current_user.last_name%></h2>
    <p> <%= current_user.friends(current_user.id).count %> friends </p>
  </div>
</div>
<br>

<div class="card shadow-sm mx-auto" style="max-width:600px">
  <div class="card-body">
    <ul class="nav nav-tabs" id="myTab" role="tablist">
      <li class="nav-item">
        <a class="nav-link active" id="home-tab" data-toggle="tab" href="#home" role="tab" aria-controls="home" aria-selected="true">Requests</a>
      </li>
      <li class="nav-item">
        <a class="nav-link" id="profile-tab" data-toggle="tab" href="#profile" role="tab" aria-controls="profile" aria-selected="false">Sent</a>
      </li>
      <li class="nav-item">
        <a class="nav-link" id="contact-tab" data-toggle="tab" href="#friends" role="tab" aria-controls="friends" aria-selected="false">Suggestions</a>
      </li>
    </ul>
    <div class="tab-content" id="myTabContent">
      <div class="tab-pane fade show active" id="home" role="tabpanel" aria-labelledby="home-tab">
        <br>
        <%= render 'friend_requests' %>
      </div>
    
      <div class="tab-pane fade" id="profile" role="tabpanel" aria-labelledby="profile-tab">
        <br>
        <%= render 'sent_requests' %>
        <br>
      </div>
    
      <div class="tab-pane fade" id="friends" role="tabpanel" aria-labelledby="contact-tab">
        <br>
        <%= render 'all_users', users: @users%>
      </div>
    </div>
      </div>
</div>

app/views/users/show.html.erb
  <div class="card shadow-sm mx-auto" style="max-width:600px">
    <div class="card-body">
      <h2> <%= @user.first_name%> <%= @user.last_name%></h2>
      <p> <%= @user.friends(@user.id).count %> friends </p>
      <% if @user == current_user %>
        <%= link_to edit_user_path, class: "btn btn-primary btn-sm" do %>
          <div><svg xmlns="http://www.w3.org/2000/svg" width="16" height="16" fill="currentColor" class="bi bi-pencil-fill" viewBox="0 0 16 16">
          <path d="M12.854.146a.5.5 0 0 0-.707 0L10.5 1.793 14.207 5.5l1.647-1.646a.5.5 0 0 0 0-.708l-3-3zm.646 6.061L9.793 2.5 3.293 9H3.5a.5.5 0 0 1 .5.5v.5h.5a.5.5 0 0 1 .5.5v.5h.5a.5.5 0 0 1 .5.5v.5h.5a.5.5 0 0 1 .5.5v.207l6.5-6.5zm-7.468 7.468A.5.5 0 0 1 6 13.5V13h-.5a.5.5 0 0 1-.5-.5V12h-.5a.5.5 0 0 1-.5-.5V11h-.5a.5.5 0 0 1-.5-.5V10h-.5a.499.499 0 0 1-.175-.032l-.179.178a.5.5 0 0 0-.11.168l-2 5a.5.5 0 0 0 .65.65l5-2a.5.5 0 0 0 .168-.11l.178-.178z"/>
          </svg>
            Edit profile
          </div>
        <% end %>

      <% elsif current_user.friend?(@user.id, current_user.id) %>
        
          <div class="btn btn-secondary  btn-sm d-inline-block" style="pointer-events: none" ><svg xmlns="http://www.w3.org/2000/svg" width="16" height="16" fill="currentColor" class="bi bi-person-check-fill" viewBox="0 0 16 16">
            <path fill-rule="evenodd" d="M15.854 5.146a.5.5 0 0 1 0 .708l-3 3a.5.5 0 0 1-.708 0l-1.5-1.5a.5.5 0 0 1 .708-.708L12.5 7.793l2.646-2.647a.5.5 0 0 1 .708 0z"/>
            <path d="M1 14s-1 0-1-1 1-4 6-4 6 3 6 4-1 1-1 1H1zm5-6a3 3 0 1 0 0-6 3 3 0 0 0 0 6z"/>
            </svg>
            Friends
          </div>
        
          <div data-controller="posts" class="d-inline-block">
            <%= button_to @friendship, method: :delete, class: "btn btn-outline-danger btn-sm ", data: { action: "click->posts#delete" } do %>
                <span>
                  <svg xmlns="http://www.w3.org/2000/svg" width="16" height="16" fill="currentColor" class="bi bi-person-x-fill" viewBox="0 0 16 16">
                  <path fill-rule="evenodd" d="M1 14s-1 0-1-1 1-4 6-4 6 3 6 4-1 1-1 1H1zm5-6a3 3 0 1 0 0-6 3 3 0 0 0 0 6zm6.146-2.854a.5.5 0 0 1 .708 0L14 6.293l1.146-1.147a.5.5 0 0 1 .708.708L14.707 7l1.147 1.146a.5.5 0 0 1-.708.708L14 7.707l-1.146 1.147a.5.5 0 0 1-.708-.708L13.293 7l-1.147-1.146a.5.5 0 0 1 0-.708z"/>
                  </svg> Unfriend 
                </span>
            <% end %> 
          </div>
          
       
      <% elsif current_user.friend_already_requested?(@user.id, current_user.id) %>
        <div class="btn btn-secondary btn-sm" style="pointer-events: none"><svg xmlns="http://www.w3.org/2000/svg" width="16" height="16" fill="currentColor" class="bi bi-person-check-fill" viewBox="0 0 16 16">
          <path fill-rule="evenodd" d="M15.854 5.146a.5.5 0 0 1 0 .708l-3 3a.5.5 0 0 1-.708 0l-1.5-1.5a.5.5 0 0 1 .708-.708L12.5 7.793l2.646-2.647a.5.5 0 0 1 .708 0z"/>
          <path d="M1 14s-1 0-1-1 1-4 6-4 6 3 6 4-1 1-1 1H1zm5-6a3 3 0 1 0 0-6 3 3 0 0 0 0 6z"/>
          </svg>
            Request sent
        </div>
      <% elsif current_user.friend_already_invited?(@user.id, current_user.id) %>
        <%= button_to friendships_path, method: :post, params: { friend_b_id: @user.id }, class:"btn btn-success btn-sm" do %>
          <div><svg xmlns="http://www.w3.org/2000/svg" width="16" height="16" fill="currentColor" class="bi bi-person-plus-fill" viewBox="0 0 16 16">
            <path d="M1 14s-1 0-1-1 1-4 6-4 6 3 6 4-1 1-1 1H1zm5-6a3 3 0 1 0 0-6 3 3 0 0 0 0 6z"/>
            <path fill-rule="evenodd" d="M13.5 5a.5.5 0 0 1 .5.5V7h1.5a.5.5 0 0 1 0 1H14v1.5a.5.5 0 0 1-1 0V8h-1.5a.5.5 0 0 1 0-1H13V5.5a.5.5 0 0 1 .5-.5z"/>
            </svg>
            Accept friend request
          </div>
        <% end %>
      <% else %>
        <%= button_to friend_requests_path, method: :post, params: { recipient_id: @user.id }, class:"btn btn-primary btn-sm" do %>
          <div><svg xmlns="http://www.w3.org/2000/svg" width="16" height="16" fill="currentColor" class="bi bi-person-plus-fill" viewBox="0 0 16 16">
            <path d="M1 14s-1 0-1-1 1-4 6-4 6 3 6 4-1 1-1 1H1zm5-6a3 3 0 1 0 0-6 3 3 0 0 0 0 6z"/>
            <path fill-rule="evenodd" d="M13.5 5a.5.5 0 0 1 .5.5V7h1.5a.5.5 0 0 1 0 1H14v1.5a.5.5 0 0 1-1 0V8h-1.5a.5.5 0 0 1 0-1H13V5.5a.5.5 0 0 1 .5-.5z"/>
            </svg>
            Send friend request
          </div>
        <% end %>
      <% end %> 

    </div>
  </div>
<br>
<% if current_user.friend?(@user.id, current_user.id) || current_user == @user %>
  <div class="card shadow-sm mx-auto" style="max-width:600px">
    <div class="card-body">
      <ul class="nav nav-tabs" id="myTab" role="tablist">
        <li class="nav-item">
          <a class="nav-link active" id="home-tab" data-toggle="tab" href="#home" role="tab" aria-controls="home" aria-selected="true">About</a>
        </li>
        <li class="nav-item">
          <a class="nav-link" id="profile-tab" data-toggle="tab" href="#profile" role="tab" aria-controls="profile" aria-selected="false">Posts</a>
        </li>
        <li class="nav-item">
          <% if @user == current_user %>
            <a class="nav-link" id="contact-tab" data-toggle="tab" href="#contact" role="tab" aria-controls="contact" aria-selected="false"> My Friends</a>
          <% else %>
            <a class="nav-link" id="contact-tab" data-toggle="tab" href="#contact" role="tab" aria-controls="contact" aria-selected="false"> Friends</a>
          <% end %>  
        </li>
      </ul>
      <div class="tab-content" id="myTabContent">
        <div class="tab-pane fade show active" id="home" role="tabpanel" aria-labelledby="home-tab">
          <br>
          <%= render 'about', user: @user %>
          <% if current_user == @user %>
            <br>

            <%= link_to edit_user_registration_path, class: "btn btn-danger btn-sm" do %>
              <div><svg xmlns="http://www.w3.org/2000/svg" width="16" height="16" fill="currentColor" class="bi bi-gear-fill" viewBox="0 0 16 16">
              <path d="M9.405 1.05c-.413-1.4-2.397-1.4-2.81 0l-.1.34a1.464 1.464 0 0 1-2.105.872l-.31-.17c-1.283-.698-2.686.705-1.987 1.987l.169.311c.446.82.023 1.841-.872 2.105l-.34.1c-1.4.413-1.4 2.397 0 2.81l.34.1a1.464 1.464 0 0 1 .872 2.105l-.17.31c-.698 1.283.705 2.686 1.987 1.987l.311-.169a1.464 1.464 0 0 1 2.105.872l.1.34c.413 1.4 2.397 1.4 2.81 0l.1-.34a1.464 1.464 0 0 1 2.105-.872l.31.17c1.283.698 2.686-.705 1.987-1.987l-.169-.311a1.464 1.464 0 0 1 .872-2.105l.34-.1c1.4-.413 1.4-2.397 0-2.81l-.34-.1a1.464 1.464 0 0 1-.872-2.105l.17-.31c.698-1.283-.705-2.686-1.987-1.987l-.311.169a1.464 1.464 0 0 1-2.105-.872l-.1-.34zM8 10.93a2.929 2.929 0 1 1 0-5.86 2.929 2.929 0 0 1 0 5.858z"/>
              </svg>
                Update account info
              </div>
            <% end %>

          <% end %>
        </div>
        <div class="tab-pane fade" id="profile" role="tabpanel" aria-labelledby="profile-tab">
          <br>
          <% @user.posts.each do |post| %>
            <%= render post %>
          <% end %>
        </div>
        <div class="tab-pane fade" id="contact" role="tabpanel" aria-labelledby="contact-tab">
          <br>
          <%= render 'friends', user: @user %>
        </div>
      </div>
    </div>
  </div>
 

<% else %>
  <div class="card shadow-sm mx-auto" style="max-width:600px">
    <h2 class="card-header">Info</h2>
    <div class="card-body">
      <% unless @user.location == "" || @user.location == nil %>
        <p>Lives in <strong><%= @user.location %></p></strong>
      <% end %>
      <% unless @user.birthday == "" || @user.birthday == nil %>
        <p>Birthday <strong><%= @user.birthday.strftime("%B %d, %Y") %></p></strong>
      <% end %>
    </div>
  </div>
<% end %>
<br>  
<div class="card shadow-sm mx-auto mb-3" style="max-width:600px"> 
  <div class="card-body">
    <%= link_to "Back", :back , class: "btn btn-secondary" %>
    <%= link_to "Home", root_path, class: "btn btn-primary" %>
   </div>
</div>