config/routes.rb
Rails.application.routes.draw do
  resources :posts do
    resources :comments
  end
  devise_for :users
  resources :users
  resources :friend_requests
  resources :friendships, only: [:create, :destroy]
  resources :comments
  
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  root to: "posts#index"
end

app/models/post.rb
class Post < ApplicationRecord
  validates :body, presence: true

  belongs_to :user

  has_many :comments,
           as: :commentable,
           dependent: :destroy


  def full_name(user)
    first_name = user.first_name
    last_name = user.last_name
    first_name + last_name
  end
end

app/controllers/posts_controller.rb
class PostsController < ApplicationController
  before_action :set_post, only: %i[ show edit update destroy ]
  before_action :authenticate_user!, except: [:index, :show]

  # GET /posts or /posts.json
  def index
    @posts = Post.all.order("created_at DESC")
    @post = Post.new
    
  end

  # GET /posts/1 or /posts/1.json
  def show
  end

  # GET /posts/new
  def new
    @post = current_user.posts.build
  end

  # GET /posts/1/edit
  def edit
  end

  # POST /posts or /posts.json
  def create
    @post = current_user.posts.build(post_params)

    respond_to do |format|
      if @post.save
        format.html { redirect_to root_path, notice: "Post was successfully created." }
        format.json { render :show, status: :created, location: @post }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @post.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /posts/1 or /posts/1.json
  def update
    respond_to do |format|
      if @post.update(post_params)
        format.html { redirect_to post_url(@post), notice: "Post was successfully updated." }
        format.json { render :show, status: :ok, location: @post }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @post.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /posts/1 or /posts/1.json
  def destroy
    @post.destroy

    respond_to do |format|
      format.html { redirect_to posts_url, notice: "Post was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_post
      @post = Post.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def post_params
      params.require(:post).permit(:body, :user_id)
    end
end

app/helpers/posts_helper.rb
module PostsHelper
end

app/views/posts/_form.html.erb
<div class="card shadow-sm mx-auto" style="max-width:600px">
  <div class="card-body">
    <%= form_with(model: post) do |form| %>
      <% if post.errors.any? %>
        <div style="color: red">
          <h2><%= pluralize(post.errors.count, "error") %> prohibited this post from being saved:</h2>
    
          <ul>
            <% post.errors.each do |error| %>
              <li><%= error.full_message %></li>
            <% end %>
          </ul>
        </div>
      <% end %>
    
      <div class="form-group">
        <%= %>
        <%= form.text_area :body, autofocus: true, placeholder: "What's on your mind, #{current_user.first_name}?", class: "form-control" %>
      </div>
      <div>

      
        <%= form.submit "Post", class:'btn btn-primary'%>
      </div>
    <% end %>
  </div>
</div>  

app/views/posts/_post.html.erb
<div id="<%= dom_id post %>">

  <div class="card shadow-sm mx-auto" style="max-width:600px">
    <div class="card-header bg-white">
    
      <strong><%= link_to (post.user.first_name + " " + post.user.last_name), user_path(post.user.id)%></strong>
      <br>
      
      <small class="text-muted"><%= post.created_at.in_time_zone("America/New_York").strftime("%B %d, %Y at %l:%M %P %Z") %></small>
    </div>
    <div class="card-body">
    <p class="card-text"><%= post.body %></p>
    <hr>
    <%= render 'comments/comment', post: post %>
    
    <%= link_to "Add comment", post, class: "btn btn-secondary btn-sm d-inline-block" %>
    
    <% if post.user.id == current_user.id %>
      <div class="d-inline-block" data-controller="posts">  
        <%= button_to post, method: :delete, class: "btn btn-danger btn-sm", data: { action: "click->posts#delete" } do %>
          <div><span><svg xmlns="http://www.w3.org/2000/svg" width="16" height="16" fill="currentColor" class="bi bi-trash3-fill" viewBox="0 0 16 16">
          <path d="M11 1.5v1h3.5a.5.5 0 0 1 0 1h-.538l-.853 10.66A2 2 0 0 1 11.115 16h-6.23a2 2 0 0 1-1.994-1.84L2.038 3.5H1.5a.5.5 0 0 1 0-1H5v-1A1.5 1.5 0 0 1 6.5 0h3A1.5 1.5 0 0 1 11 1.5Zm-5 0v1h4v-1a.5.5 0 0 0-.5-.5h-3a.5.5 0 0 0-.5.5ZM4.5 5.029l.5 8.5a.5.5 0 1 0 .998-.06l-.5-8.5a.5.5 0 1 0-.998.06Zm6.53-.528a.5.5 0 0 0-.528.47l-.5 8.5a.5.5 0 0 0 .998.058l.5-8.5a.5.5 0 0 0-.47-.528ZM8 4.5a.5.5 0 0 0-.5.5v8.5a.5.5 0 0 0 1 0V5a.5.5 0 0 0-.5-.5Z"/>
          </svg> Delete post</span></div>
        <% end %>
      </div>  
    <% end %>

    </div>
  </div>
  <br>
</div>

app/views/posts/index.html.erb
<% if user_signed_in?%>
  <div> 
 
    <%= render "form", post: @post %>
    
    <br/>
    <div id="posts">
      <% @posts.each do |post| %>
  
        <% if post.user.friend?(post.user.id, current_user.id) || post.user.id == current_user.id%>
          <%= render post %>
        <% end %>   
      <% end %>
    </div>
  </div>
<% else %>

  <% controller.redirect_to new_user_session_path %>
  
<% end %>

app/views/posts/new.html.erb
<% if @post.errors.any? %>
  <div class="alert alert-warning" role="alert">
      <% @post.errors.each do |error| %>
          <li><%= error.full_message %></li>
      <% end %>
</div>
<% end %>
<div>
  <%= link_to "Back", :back , class:'btn btn-secondary' %>
</div>

app/views/posts/show.html.erb
<div class="card shadow-sm mx-auto mb-3" style="max-width:600px">
  <div class="card-header">
    <strong><%= link_to (@post.user.first_name + " " + @post.user.last_name), user_path(@post.user.id)%></strong>
    <br>
    <%= @post.created_at.in_time_zone("America/New_York").strftime("%B %d, %Y at %l:%M %P %Z") %>
  </div>
  <div class="card-body">
    <p class="card-text"><%= @post.body %></p>
    <%= render 'comments/comment', post: @post %>
    <%= render 'comments/form', comment: @post.comments.build, submit: 'Comment' %>
  </div>
</div>  
<div class="card shadow-sm mx-auto mb-3" style="max-width:600px">
  <div class="card-body">
  <%= link_to "Back to posts", posts_path , class: "btn btn-secondary" %>
  </div>
</div>